---
- hosts: localmachine
  become: true
  tasks:
    - name: Install python
      apt:
        name: python-pip
        state: present
    - name: Install docker-py python module
      pip:
        name: docker-py
        state: present
    - name: Start Container
      docker_container:
        name: maven-web-app
        image: "nickeynicks/maven-web-app:{{DOCKER_TAG}}"
        state: started
        published_ports:
        - 0.0.0.0:8002:8080
