apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-web-app-deploy
  labels: 
    app: maven-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: maven-web-app
  template:
    metadata:
      labels:
        app: maven-web-app
    spec:
      containers:
      - name: maven-web-app
        image: nickeynicks/maven-web-app:2.0.2
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mavenapp-svc
spec:
  selector:
    app: maven-web-app
  type: LoadBalancer
  ports:  
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30020
