apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app-deploy
  labels: 
    app: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
      - name: web-app
        image: nickeynicks/web-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: webapp-svc
spec:
  selector:
    app: web-app
  type: LoadBalancer
  ports:  
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30021
